### ISSUE TITLE
Snapchat++

### ISSUE THREAD

**Issue by mikededo4** [JMccormick264/PPAppsIPARepo#35] opened 2017-05-21 11:34 UTC
Whenever I close app on Snapchat it resets the whole app. All my settings are undone. Furthermore 50 second recording does not work. It'll record but then won't show. Thank you for your hard work.

**Comment by mikededo4** [comment] 2017-05-21 11:35
Oh sorry this is the ipa on ipasigner

**Comment by mikededo4** [comment] 2017-05-21 11:35
No duplicate

**Comment by tylercain** [comment] 2017-05-21 19:35
I'm having the same problem with this on snapchat and Instagram

**Comment by JMccormick264** [comment] 2017-05-21 19:43
Okay. Since this is on ipasigner, I cannot fix it and I am not sure Unlim can. Since we both don't don't own the site or run it. So we don't control and can't control what ipas go up on it. Still not sure how he got notifications to work. But that may be the cause because I haven't had this issue with the IPA sideloaded from impactor.

**Comment by mikededo4** [comment] 2017-05-21 19:44
Do you know who we can contact to get a fix ?

**Comment by mikededo4** [comment] 2017-05-21 19:44
Or to report it ?

**Comment by mrkiller2010** [comment] 2017-05-21 23:12
Yeah, every apps setting gets resetted whenever you close it, can you contact the owner of the website or give us his twitter or email? Thanks

**Comment by JMccormick264** [comment] 2017-05-22 02:49
I do not know his ema, twitter, etc. I wish I did. I have been trying to find it.

**Comment by rikianastasoski** [comment] 2017-05-22 18:56
@JMccormick264 this also happens for the ipa's from this github, instagram resets every time i close it from app switcher :/ and also after some update when i sideload instagram or snapchat with cydia impactor, it doesnt say completed it just gets stuck on "GeneratingApplicationMap" but the app is sideloaded so i just close it

**Comment by JMccormick264** [comment] 2017-05-22 18:58
@rikianastasoski That last comment is because of Impactor and iOS 10.3. It will still install. that is normal. As for the signing out of the ad removal, Unlim is looking into it. I have made him aware. This is happening to others too. and not just on one IPA.

**Comment by rikianastasoski** [comment] 2017-05-22 19:43
@JMccormick264 also since 2-3 versions ago a lot of videos (maybe all) dont get downloaded. it says success but it doesnt show in photos, tnx for all the work!

**Comment by JMccormick264** [comment] 2017-05-22 19:45
Are you sideload or JB?

**Comment by mrkiller2010** [comment] 2017-05-22 20:05
I'm sideloaded and like every app from ipasigner.io gets reseted when u close the app.
Also when you open a snapchat and press the eye you have to refresh your snaps to make the snap go away, does eni know that so he can fix it?

**Comment by rikianastasoski** [comment] 2017-05-22 21:54
@JMccormick264 im sideloaded i downgraded to a version from april so im good for now

**Comment by amkrafie** [comment] 2017-05-23 07:31
@JMccormick264 

Whenever I close the app from the appswitcher everything resets, all my settings and I get logged out of ad removal. I'm sideloaded with snapchat++ form this github.

**Comment by JMccormick264** [comment] 2017-05-26 20:39
This should be fixed. But snapchat++ is no longer working due to DRM.

**Closed by JMccormick264** 2017-05-26 20:39 UTC
